In [1]:
import numpy as np
import torch


In [2]:
a = torch.ones(3)
print(a)
print()
print(a[1])
print()
print(float(a[1]))
a[2] = 2
print(a)


tensor([1., 1., 1.])

tensor(1.)

1.0
tensor([1., 1., 2.])


In [ ]:
points = torch.Tensor([[4, 1], [5, 3], [2, 1]])
print(points)
print(points.shape)


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])


tensor(1.)

In [ ]:
random_tensor = torch.rand([6, 2])


In [ ]:
print(random_tensor)


tensor([[0.5440, 0.9400],
        [0.4849, 0.2689],
        [0.7807, 0.3816],
        [0.5592, 0.7838],
        [0.5489, 0.3646],
        [0.9765, 0.9042]])


In [ ]:
random_tensor[1:4:2]


tensor([[0.4849, 0.2689],
        [0.5592, 0.7838]])

In [ ]:
random_tensor[None].shape


torch.Size([1, 6, 2])

## MISC CODE

In [ ]:
x = torch.ones(2,2, requires_grad=True)
print(x)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)
print(y.grad_fn)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
z = y * y * 3
out = z.mean()
print(z)
print(out)


In [ ]:
out.backward()


In [ ]:
print(x.grad)

tensor([[9., 9.],
        [9., 9.]])
