In [1]:
import numpy as np
import torch


In [2]:
torch.cuda.is_available()

True

In [ ]:
a = torch.ones(3)
print(a)
print()
print(a[1])
print()
print(float(a[1]))
a[2] = 2
print(a)


tensor([1., 1., 1.])

tensor(1.)

1.0
tensor([1., 1., 2.])


In [ ]:
points = torch.Tensor([[4, 1], [5, 3], [2, 1]])
print(points)
print(points.shape)


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])


In [ ]:
random_tensor = torch.rand([6, 2])


In [ ]:
print(random_tensor)


tensor([[0.6124, 0.1686],
        [0.1162, 0.0800],
        [0.8860, 0.6838],
        [0.6044, 0.6465],
        [0.7578, 0.0126],
        [0.2489, 0.3772]])


In [ ]:
random_tensor[1:4:2]


tensor([[0.1162, 0.0800],
        [0.6044, 0.6465]])

In [ ]:
print(random_tensor.shape)
random_tensor[None].shape


torch.Size([6, 2])


torch.Size([1, 6, 2])

## MISC CODE

In [ ]:
x = torch.ones(2,2, requires_grad=True)
print(x)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)
print(y.grad_fn)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
z = y * y * 3
out = z.mean()
print(z)
print(out)


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
out.backward()


In [ ]:
print(x.grad)

tensor([[9., 9.],
        [9., 9.]])


In [ ]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

batch_t = torch.randn(2, 3, 5, 5)


Sometimes **RGB** channel are in 0 dimension, and sometime they are in 1.

But we can generalize by counting from the end: they are always in dimension -3


In [ ]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
print(img_gray_naive.shape, batch_gray_naive.shape)


torch.Size([5, 5]) torch.Size([2, 5, 5])


In [ ]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [ ]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(batch_weights.shape, batch_t.shape, unsqueezed_weights.shape)


torch.Size([2, 3, 5, 5]) torch.Size([2, 3, 5, 5]) torch.Size([3, 1, 1])


### TENSOR DTYPE

In [ ]:
double_pt = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)


In [ ]:
short_points.dtype


torch.int16

### CHANGING OR SETTING DTYPE

In [ ]:
double_points = torch.ones(10,2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)


### BASIC OPERATIONS

In [ ]:
# Transpose
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
print(a.shape, a_t.shape)


torch.Size([3, 2]) torch.Size([2, 3])


In [ ]:
# Cloning
# A change in sub tensor will change the main tensor also. 
a = torch.tensor([[10,5], [8,7], [12,15], [3,4]])
sub_t = a[2]
sub_t[0] = 100
print(a)



tensor([[ 10,   5],
        [  8,   7],
        [100,  15],
        [  3,   4]])


In [ ]:
# To avoid the above, we will clone the sub tensor
a = torch.tensor([[10,5], [8,7], [12,15], [3,4]])
sub_t = a[2].clone()
sub_t[0] = 100
print(a)
print()
print(sub_t)

tensor([[10,  5],
        [ 8,  7],
        [12, 15],
        [ 3,  4]])

tensor([100,  15])


### GPU (CUDA)

In [3]:
points_gpu = torch.tensor([[4,1], [5,3], [2,1]], device="cuda")

# on cpu
points = torch.tensor([[4,1], [5,3], [2,1]])
# shifting to gpu
points_gpu1 = points.to(device="cuda")


### SAVING & LOADING WITH PYTORCH

In [8]:
# Saving
torch.save(points_gpu, "./ourpoints.t")

# Loading
load_points = torch.load("./ourpoints.t")
print(load_points)


tensor([[4, 1],
        [5, 3],
        [2, 1]], device='cuda:0')


### EXCERCISE

#### Q1

In [14]:
a = torch.tensor([x for x in range(9)])
print(a)
print()
print("size", a.size())
print("stride", a.stride())
print("offset", a.storage_offset())


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

size torch.Size([9])
stride (1,)
offset 0


In [17]:
b = a.view(3, 3)
print(b)
print()
print(a.storage())
print()
print(b.storage())


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]


In [20]:
c = b[1:,1:]
print(c)
print(c.size())
print(c.stride())
print(c.storage_offset())


tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
(3, 1)
4


#### Q2

In [22]:
a = torch.tensor([x for x in range(9)], dtype=torch.double)
torch.sqrt(a)


tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284],
       dtype=torch.float64)