In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.nn import Linear
from torch.autograd import Variable


In [ ]:
my_layer = Linear(in_features=10, out_features=5, bias=True)

inp = Variable(torch.randn(1,10))
my_layer(inp)
my_layer.weight


tensor([[ 0.3780,  1.2080,  0.1245, -0.5090, -0.6081]],
       grad_fn=<AddmmBackward>)

In [ ]:
my_layer.weight
my_layer.shape
my_layer.bias


Parameter containing:
tensor([-0.3144,  0.0075, -0.0519, -0.1754,  0.0412], requires_grad=True)

In [ ]:
my_layer1 = Linear(10,5)
my_layer2 = Linear(5,2)
my_layer2(my_layer1(inp))


tensor([[-0.4457, -0.0809]], grad_fn=<AddmmBackward>)

## ACTIVATIONS

In [ ]:
sample_data = Variable(torch.Tensor([[1, 2, -1, -1]]))
my_relu = nn.ReLU()
my_relu(sample_data)


tensor([[1., 2., 0., 0.]])

## NEURAL NETWORK

In [ ]:
class my_first_net(nn.Module):

  def __init__(self, input_size, hidden_size, output_size):
    super(my_first_net.self).__init__()
    self.layer1 = Linear(input_size, hidden_size)
    self.layer2 = Linear(hidden_size, output_size)
  
  def __forward__(self, input):
    out = self.layer1(input)
    out = nn.ReLU(out)
    out = self.layer2(out)
    return out



## Loss Functions

In [ ]:
loss = nn.MSELoss()
input = Variable(torch.randn(3,5), requires_grad=True)
target = Variable(torch.randn(3,5))
output = loss(input, target)
output.backward()
print(output)


### Cross Entropy Loss

In [ ]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3,5), requires_grad=True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input, target)
print(output)



tensor(2.3840, grad_fn=<NllLossBackward>)


## OPTIMIZER

In [ ]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.01)


## KAGGLE

In [ ]:
!mkdir -p ~/.kaggle && cp -r drive/My\ Drive/kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json


In [ ]:
!pip uninstall -y kaggle
!pip install --upgrade pip
!pip install kaggle==1.5.6
!kaggle -v

In [ ]:
!kaggle competitions download -c dogs-vs-cats
!unzip dogs-vs-cats.zip
!mkdir cats_dogs
!mv dogs-vs-cats.zip cats_dogs
!rm -f *.zip
!cd cats_dogs; unzip dogs-vs-cats.zip
!cd cats_dogs; unzip test1.zip; unzip train.zip


In [29]:
!cd cats_dogs/train; ls | tail


dog.9993.jpg
dog.9994.jpg
dog.9995.jpg
dog.9996.jpg
dog.9997.jpg
dog.9998.jpg
dog.9999.jpg
dog.999.jpg
dog.99.jpg
dog.9.jpg


In [48]:
from torchvision import datasets, transforms, models
import torch

In [49]:
data_dir = "/content/cats_dogs"

train_transforms = transforms.Compose([transforms.RandomRotation(30),
                                       transforms.RandomResizedCrop(224),
                                       transforms.RandomHorizontalFlip(),
                                       transforms.ToTensor(),
                                       transforms.Normalize([0.485, 0.456, 0.406],
                                                            [0.229, 0.224, 0.225])])

test_transforms = transforms.Compose([transforms.Resize(255),
                                      transforms.CenterCrop(224),
                                      transforms.ToTensor(),
                                      transforms.Normalize([0.485, 0.456, 0.406],
                                                           [0.229, 0.224, 0.225])])

# Pass transforms in here, then run the next cell to see how the transforms look
train_data = datasets.ImageFolder(data_dir + '/train/', transform=train_transforms)
# test_data = datasets.ImageFolder(data_dir + '/test1/', transform=test_transforms)

trainloader = torch.utils.data.DataLoader(train_data, batch_size=64, shuffle=True)
# testloader = torch.utils.data.DataLoader(test_data, batch_size=64)


In [50]:
!cd cats_dogs/test1; ls | head

10000.jpg
10001.jpg
10002.jpg
10003.jpg
10004.jpg
10005.jpg
10006.jpg
10007.jpg
10008.jpg
10009.jpg


In [46]:
!cd cats_dogs/train; mkdir dog; mkdir cat; mv cat.* cat; mv dog.* dog
!cd cats_dogs/test1; mkdir dog; mkdir cat; mv cat.* cat; mv dog.* dog


In [59]:
data_iter = iter(trainloader)

In [60]:
images, labels = next(data_iter)

tensor([[[-1.5357, -0.0629, -0.0629,  ...,  0.3823,  0.3994,  0.4166],
         [-1.5357, -0.0801, -0.0629,  ...,  0.3823,  0.3823,  0.3994],
         [-1.5528, -0.0972, -0.0801,  ...,  0.3652,  0.3652,  0.3823],
         ...,
         [-0.0287,  0.0227,  0.1254,  ..., -0.0458,  0.0569, -1.5014],
         [-0.0801, -0.0629,  0.0741,  ..., -0.1314, -0.0458, -1.5185],
         [-0.0629, -0.1143,  0.0398,  ..., -0.0287, -0.0972, -1.5528]],

        [[-1.4755, -0.0749, -0.0749,  ...,  0.3627,  0.3803,  0.3978],
         [-1.4755, -0.0924, -0.0924,  ...,  0.3627,  0.3627,  0.3803],
         [-1.4930, -0.1275, -0.1099,  ...,  0.3452,  0.3452,  0.3627],
         ...,
         [ 0.1176,  0.1702,  0.2752,  ...,  0.1001,  0.2052, -1.3880],
         [ 0.0651,  0.0826,  0.2227,  ...,  0.0126,  0.1001, -1.4055],
         [ 0.1001,  0.0476,  0.1877,  ...,  0.1176,  0.0476, -1.4580]],

        [[-1.1770,  0.4091,  0.4091,  ...,  0.9145,  0.9319,  0.9494],
         [-1.1770,  0.4091,  0.4265,  ...,  0